# Generated by Django 5.2.1 on 2025-06-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0002_sports_alter_club_id_club_sports_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='min_players',
        ),
        migrations.AlterField(
            model_name='sports',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ClubSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.PositiveIntegerField(verbose_name=2)),
                ('available_slots', models.PositiveIntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_booking.sports')),
            ],
        ),
        migrations.CreateModel(
            name='SportsClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sports', models.ManyToManyField(related_name='clubs', through='app_booking.ClubSports', to='app_booking.sports')),
            ],
        ),
        migrations.AddField(
            model_name='clubsports',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_booking.sportsclub'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.AlterUniqueTogether(
            name='clubsports',
            unique_together={('club', 'sport')},
        ),
    ]
