# Generated by Django 5.2.1 on 2025-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0003_remove_sports_description_remove_sports_min_players_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_players', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='sportsclub',
            name='sports',
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='sports_offered',
            field=models.ManyToManyField(related_name='SportsOffered', to='app_booking.sport'),
        ),
        migrations.DeleteModel(
            name='ClubSports',
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
    ]
