# Generated by Django 5.2.1 on 2025-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0004_sport_remove_sportsclub_sports_sportsclub_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsclub',
            name='sports_offered',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='sports_offered',
            field=models.CharField(choices=[('Badminton', 'Badminton'), ('Cricket', 'Cricket'), ('Tennis', 'Tennis')], null=True),
        ),
    ]
