# Generated by Django 5.2.1 on 2025-06-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0005_remove_sportsclub_sports_offered_delete_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsclub',
            name='sports_offered',
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=100)),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Club', to='app_booking.sportsclub')),
            ],
        ),
    ]
