# Generated by Django 5.2.1 on 2025-06-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0006_remove_sportsclub_sports_offered_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='club_name',
        ),
    ]
