# Generated by Django 5.2.1 on 2025-06-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0008_sport_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='club_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='club', to='app_booking.sportsclub'),
        ),
    ]
