# Generated by Django 5.2.1 on 2025-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0009_alter_sport_club_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='club_name',
        ),
        migrations.AddField(
            model_name='sport',
            name='club_name',
            field=models.ManyToManyField(to='app_booking.sportsclub'),
        ),
    ]
