# Generated by Django 5.2.1 on 2025-06-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0010_remove_sport_club_name_sport_club_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
