# Generated by Django 5.2.1 on 2025-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0011_delete_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsclub',
            name='is_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
