# Generated by Django 5.2.1 on 2025-06-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0013_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='sportsclub',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='sportsclub',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='slot',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app_booking.sportsclub'),
        ),
        migrations.AddField(
            model_name='slot',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_booking.sport'),
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='sports_offered',
            field=models.ManyToManyField(related_name='clubs', to='app_booking.sport'),
        ),
    ]
