# Generated by Django 5.2.1 on 2025-06-03 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0014_slot_sport_delete_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='book_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_time',
            field=models.TextField(choices=[('1', '08:00 - 09:00'), ('2', '09:00 - 10:00'), ('3', '10:00 - 11:00'), ('4', '11:00 - 12:00'), ('5', '12:00 - 13:00'), ('6', '13:00 - 14:00'), ('7', '14:00 - 15:00'), ('8', '15:00 - 16:00'), ('9', '16:00 - 17:00'), ('10', '17:00 - 18:00'), ('11', '18:00 - 19:00'), ('12', '19:00 - 20:00')], default=2),
            preserve_default=False,
        ),
    ]
