# Generated by Django 5.2.1 on 2025-06-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0015_remove_slot_end_time_remove_slot_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_date',
            field=models.DateField(default='2025-06-04'),
            preserve_default=False,
        ),
    ]
